language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install: composer self-update

install: composer install --optimize-autoloader --no-interaction

before_script: mysql -e 'create database `estaty_test`;'

script: phpunit --coverage-clover=coverage.clover

after_script: [ -f coverage.clover ] && wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
