language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install: composer self-update

install: composer install --no-dev --optimize-autoloader --no-interaction

before_script: mysql -e 'create database `estaty_test`;'

script: phpunit
