#!/usr/bin/env php
<?php

use Symfony\Component\Console;
use Doctrine\ORM\Tools\Console\ConsoleRunner;

// Initialize the Silex app
$app = require_once __DIR__.'/src/app.php';

// Get Entity Manager
$entityManager = $app['orm.em'];

$helperSet = ConsoleRunner::createHelperSet($entityManager);

$cli = new Console\Application('Doctrine Command Line Interface', \Doctrine\ORM\Version::VERSION);
$cli->setCatchExceptions(true);
$cli->setHelperSet($helperSet);

$app->register(new \Kurl\Silex\Provider\DoctrineMigrationsProvider($cli), array(
    'migrations.directory'  => __DIR__ . '/migrations',
    'migrations.name'       => 'Estaty Migrations',
    'migrations.namespace'  => 'Estaty\Migrations',
    'migrations.table_name' => 'migrations',
));

// Register All Doctrine Commands
ConsoleRunner::addCommands($cli);

// Boot app manually, because no request is executed
$app->boot();

// Run console application
$cli->run();
