<?php

namespace Estaty\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20150216231943 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');
        $this->addSql(<<<SQL
INSERT INTO `Country` (
	`name`,
	`shortCode`,
	`defaultCurrency`,
	`areaUnit`
)
VALUES
("Abkhazia", "GE-AB","RUB","square meters"),
("Afghanistan","AF","AFN","square meters"),
("Aland Islands","AX","EUR","square meters"),
("Albania","AL","ALL","square meters"),
("Algeria","DZ","DZD","square meters"),
("American Samoa","AS","USD","square feet"),
("Andorra","AD","EUR","square meters"),
("Angola","AO","AOA","square meters"),
("Anguilla","AI","XCD","square meters"),
("Antigua and Barbuda","AG","XCD","square meters"),
("Argentina","AR","ARS","square meters"),
("Armenia","AM","AMD","square meters"),
("Aruba","AW","AWG","square meters"),
("Ascension Island","SH-AC","SHP","square meters"),
("Australia","AU","AUD","square meters"),
("Austria","AT","EUR","square meters"),
("Azerbaijan","AZ","AZN","square meters"),
("Bahamas","BS","BSD","square meters"),
("Bahrain","BH","BHD","square meters"),
("Bangladesh","BD","BDT","square meters"),
("Barbados","BB","BBD","square meters"),
("Belarus","BY","BYR","square meters"),
("Belgium","BE","EUR","square meters"),
("Belize","BZ","BZD","square meters"),
("Benin","BJ","XOF","square meters"),
("Bermuda","BM","BMD","square meters"),
("Bhutan","BT","BTN","square meters"),
("Bolivia","BO","BOB","square meters"),
("Bonaire, Saint Eustatius and Saba","BQ","USD","square feet"),
("Bosnia and Herzegovina","BA","BAM","square meters"),
("Botswana","BW","BWP","square meters"),
("Brazil","BR","BRL","square meters"),
("British Indian Ocean Territory","IO","USD","square feet"),
("Brunei Darussalam","BN","BND","square meters"),
("Bulgaria","BG","BGN","square meters"),
("Burkina Faso","BF","XOF","square meters"),
("Burundi","BI","BIF","square meters"),
("Cambodia","KH","KHR","square meters"),
("Cameroon","CM","XAF","square meters"),
("Canada","CA","CAD","square feet"),
("Cape Verde","CV","CVE","square meters"),
("Cayman Islands","KY","KYD","square meters"),
("Central African Republic","CF","XAF","square meters"),
("Chad","TD","XAF","square meters"),
("Chile","CL","CLP","square meters"),
("China","CN","CNY","square meters"),
("Christmas Island","CX","AUD","square meters"),
("Cocos (Keeling) Islands","CC","AUD","square meters"),
("Colombia","CO","COP","square meters"),
("Comoros","KM","KMF","square meters"),
("Congo, The Democratic Republic of the","CD","CDF","square meters"),
("Congo, The Republic of the","CG","XAF","square meters"),
("Cook Islands","CK","NZD","square meters"),
("Costa Rica","CR","CRC","square meters"),
("Cote D'Ivoire","CI","XOF","square meters"),
("Croatia","HR","HRK","square meters"),
("Cuba","CU","CUP","square meters"),
("Curacao","CW","ANG","square meters"),
("Cyprus","CY","EUR","square meters"),
("Czech Republic","CZ","CZK","square meters"),
("Denmark","DK","DKK","square meters"),
("Djibouti","DJ","DJF","square meters"),
("Dominica","DM","XCD","square meters"),
("Dominican Republic","DO","DOP","square meters"),
("Ecuador","EC","USD","square feet"),
("Egypt","EG","EGP","square meters"),
("El Salvador","SV","USD","square feet"),
("Equatorial Guinea","GQ","XAF","square meters"),
("Eritrea","ER","ERN","square meters"),
("Estonia","EE","EUR","square meters"),
("Ethiopia","ET","ETB","square meters"),
("Falkland Islands (Malvinas)","FK","FKP","square meters"),
("Faroe Islands","FO","DKK","square meters"),
("Fiji","FJ","FJD","square meters"),
("Finland","FI","EUR","square meters"),
("France","FR","EUR","square meters"),
("French Guiana","GF","EUR","square meters"),
("French Polynesia","PF","XPF","square meters"),
("French Southern Territories","TF","EUR","square meters"),
("Gabon","GA","XAF","square meters"),
("Gambia","GM","GMD","square meters"),
("Georgia","GE","GEL","square meters"),
("Germany","DE","EUR","square meters"),
("Ghana","GH","GHS","square meters"),
("Gibraltar","GI","GIP","square meters"),
("Greece","GR","EUR","square meters"),
("Greenland","GL","DKK","square meters"),
("Grenada","GD","XCD","square meters"),
("Guadeloupe","GP","EUR","square meters"),
("Guam","GU","USD","square feet"),
("Guatemala","GT","GTQ","square meters"),
("Guernsey","GG","GBP","square feet"),
("Guinea","GN","GNF","square meters"),
("Guinea-Bissau","GW","XOF","square meters"),
("Guyana","GY","GYD","square meters"),
("Haiti","HT","HTG","square meters"),
("Honduras","HN","HNL","square meters"),
("Hong Kong","HK","HKD","square feet"),
("Hungary","HU","HUF","square meters"),
("Iceland","IS","ISK","square meters"),
("India","IN","INR","square feet"),
("Indonesia","ID","IDR","square meters"),
("Iran, Islamic Republic of","IR","IRR","square meters"),
("Iraq","IQ","IQD","square meters"),
("Ireland","IE","EUR","square meters"),
("Isle of Man","IM","GBP","square feet"),
("Israel","IL","ILS","square meters"),
("Italy","IT","EUR","square meters"),
("Jamaica","JM","JMD","square meters"),
("Japan","JP","JPY","square meters"),
("Jersey","JE","GBP","square feet"),
("Jordan","JO","JOD","square meters"),
("Kazakhstan","KZ","KZT","square meters"),
("Kenya","KE","KES","square meters"),
("Kiribati","KI","AUD","square meters"),
("Korea, Democratic People's Republic of","KP","KPW","square meters"),
("Korea, Republic of","KR","KRW","square meters"),
("Kosovo", "XK","EUR","square meters"),
("Kuwait","KW","KWD","square meters"),
("Kyrgyzstan","KG","KGS","square meters"),
("Lao People's Democratic Republic","LA","LAK","square meters"),
("Latvia","LV","EUR","square meters"),
("Lebanon","LB","LBP","square meters"),
("Lesotho","LS","LSL","square meters"),
("Liberia","LR","LRD","square meters"),
("Libya","LY","LYD","square meters"),
("Liechtenstein","LI","CHF","square meters"),
("Lithuania","LT","EUR","square meters"),
("Luxembourg","LU","EUR","square meters"),
("Macau","MO","MOP","square meters"),
("Macedonia","MK","MKD","square meters"),
("Madagascar","MG","MGA","square meters"),
("Malawi","MW","MWK","square meters"),
("Malaysia","MY","MYR","square meters"),
("Maldives","MV","MVR","square meters"),
("Mali","ML","XOF","square meters"),
("Malta","MT","EUR","square meters"),
("Marshall Islands","MH","USD","square feet"),
("Martinique","MQ","EUR","square meters"),
("Mauritania","MR","MRO","square meters"),
("Mauritius","MU","MUR","square meters"),
("Mayotte","YT","EUR","square meters"),
("Mexico","MX","MXN","square meters"),
("Micronesia, Federated States of","FM","USD","square feet"),
("Moldova, Republic of","MD","MDL","square meters"),
("Monaco","MC","EUR","square meters"),
("Mongolia","MN","MNT","square meters"),
("Montenegro","ME","EUR","square meters"),
("Montserrat","MS","XCD","square meters"),
("Morocco","MA","MAD","square meters"),
("Mozambique","MZ","MZN","square meters"),
("Myanmar","MM","MMK","square meters"),
("Namibia","NA","NAD","square meters"),
("Nauru","NR","AUD","square meters"),
("Nepal","NP","NPR","square meters"),
("Netherlands","NL","EUR","square meters"),
("New Caledonia","NC","XPF","square meters"),
("New Zealand","NZ","NZD","square meters"),
("Nicaragua","NI","NIO","square meters"),
("Niger","NE","XOF","square meters"),
("Nigeria","NG","NGN","square meters"),
("Niue","NU","NZD","square meters"),
("Norfolk Island","NF","AUD","square meters"),
("Northern Mariana Islands","MP","USD","square feet"),
("Norway","NO","NOK","square meters"),
("Oman","OM","OMR","square meters"),
("Pakistan","PK","PKR","square meters"),
("Palau","PW","USD","square feet"),
("Palestinian Territory","PS","ILS","square meters"),
("Panama","PA","PAB","square meters"),
("Papua New Guinea","PG","PGK","square meters"),
("Paraguay","PY","PYG","square meters"),
("Peru","PE","PEN","square meters"),
("Philippines","PH","PHP","square meters"),
("Pitcairn Islands","PN","NZD","square meters"),
("Poland","PL","PLN","square meters"),
("Portugal","PT","EUR","square meters"),
("Puerto Rico","PR","USD","square feet"),
("Qatar","QA","QAR","square meters"),
("Reunion","RE","EUR","square meters"),
("Romania","RO","RON","square meters"),
("Russian Federation","RU","RUB","square meters"),
("Rwanda","RW","RWF","square meters"),
("Saint Barthelemy","BL","EUR","square meters"),
("Saint Helena","SH","SHP","square meters"),
("Saint Kitts and Nevis","KN","XCD","square meters"),
("Saint Lucia","LC","XCD","square meters"),
("Saint Martin","MF","EUR","square meters"),
("Saint Pierre and Miquelon","PM","EUR","square meters"),
("Saint Vincent and the Grenadines","VC","XCD","square meters"),
("Samoa","WS","WST","square meters"),
("San Marino","SM","EUR","square meters"),
("Sao Tome and Principe","ST","STD","square meters"),
("Saudi Arabia","SA","SAR","square meters"),
("Senegal","SN","XOF","square meters"),
("Serbia","RS","RSD","square meters"),
("Seychelles","SC","SCR","square meters"),
("Sierra Leone","SL","SLL","square meters"),
("Singapore","SG","SGD","square meters"),
("Sint Maarten (Dutch part)","SX","ANG","square meters"),
("Slovakia","SK","EUR","square meters"),
("Slovenia","SI","EUR","square meters"),
("Solomon Islands","SB","SBD","square meters"),
("Somalia","SO","SOS","square meters"),
("South Africa","ZA","ZAR","square meters"),
("South Georgia and the South Sandwich Islands","GS","GBP","square feet"),
("South Sudan","SS","SSP","square meters"),
("Spain","ES","EUR","square meters"),
("Sri Lanka","LK","LKR","square meters"),
("Sudan","SD","SDG","square meters"),
("Suriname","SR","SRD","square meters"),
("Svalbard and Jan Mayen","SJ","NOK","square meters"),
("Swaziland","SZ","SZL","square meters"),
("Sweden","SE","SEK","square meters"),
("Switzerland","CH","CHF","square meters"),
("Syrian Arab Republic","SY","SYP","square meters"),
("Taiwan","TW","TWD","square meters"),
("Tajikistan","TJ","TJS","square meters"),
("Tanzania, United Republic of","TZ","TZS","square meters"),
("Thailand","TH","THB","square meters"),
("Timor-Leste","TL","USD","square feet"),
("Togo","TG","XOF","square meters"),
("Tokelau","TK","NZD","square meters"),
("Tonga","TO","TOP","square meters"),
("Trinidad and Tobago","TT","TTD","square meters"),
("Tristan da Cunha","SH-TA","SHP","square meters"),
("Tunisia","TN","TND","square meters"),
("Turkey","TR","TRY","square meters"),
("Turkmenistan","TM","TMT","square meters"),
("Turks and Caicos Islands","TC","USD","square feet"),
("Tuvalu","TV","AUD","square meters"),
("Uganda","UG","UGX","square meters"),
("Ukraine","UA","UAH","square meters"),
("United Arab Emirates","AE","AED","square meters"),
("United Kingdom","GB","GBP","square feet"),
("United States Minor Outlying Islands","UM","USD","square feet"),
("United States","US","USD","square feet"),
("Uruguay","UY","UYU","square meters"),
("Uzbekistan","UZ","UZS","square meters"),
("Vanuatu","VU","VUV","square meters"),
("Vatican City","VA","EUR","square meters"),
("Venezuela","VE","VEF","square meters"),
("Vietnam","VN","VND","square meters"),
("Virgin Islands, British","VG","USD","square feet"),
("Virgin Islands, U.S.","VI","USD","square feet"),
("Wallis and Futuna","WF","XPF","square meters"),
("Yemen","YE","YER","square meters"),
("Zambia","ZM","ZMW","square meters"),
("Zimbabwe","ZW","USD","square feet")
SQL
        );
    }

    public function down(Schema $schema)
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('TRUNCATE TABLE `Country`');
    }
}
